login:
   path: /
   controller: App\Controller\LoginController::login

logout:
   path: /logout
   controller: App\Controller\LoginController::logout

register:
   path: /registro
   controller: App\Controller\LoginController::register
   methods: [GET, POST]

register-save:
   path: /registro-save
   controller: App\Controller\LoginController::saveRegister
   methods: [GET, POST]

home:
   path: /home
   controller: App\Controller\TaskController::index
   methods: [GET]

user:
   path: /user
   controller: App\Controller\UserController::index
   methods: [GET]

task-create:
   path: /task_create
   controller: App\Controller\TaskController::crear_task
   methods: [GET, POST]

view-task:
   path: /tarea/{id}
   controller: App\Controller\TaskController::ver_tarea
   methods: [GET]

delete-task:
   path: /eliminar/{id}
   controller: App\Controller\TaskController::eliminar_tarea
   methods: [GET]

update-task:
   path: /editar/{id}
   controller: App\Controller\TaskController::editar_tarea
   methods: [GET, POST]

modificar-perfil:
   path: /modificarUser/{id}
   controller: App\Controller\UserController::modificar
   methods: [GET, POST]